version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: install tox
                command: pip install tox

            - run:
                name: version checks
                command: |
                    python --version
                    pip --version
                    virtualenv --version
                    tox --version

            - run:
                name: run tox
                command: tox

            - store_test_results:
                path: .circleci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash) -t  "f8a42945-764a-463a-86b3-6f186109e3c6"
